### ISSUE TITLE
Create a simple program to accept a number and perform basic arithmetic operations

### ISSUE THREAD

**Issue by ghost** [rollbear/basicpp#11]
Hi , I was wondering if I could make a PR of a program in C++ where the user inputs two values and basic mathematical operations are operated on the input 

Can you let me know where to store the file in the Branch ?

**Comment by rollbear** [comment]
Cool. Add them under the 'examples' directory. Look at the other examples.

**Comment by ghost** [comment]
Awesome , thank you , have a good day

hey , I apologise , I thought it was c++ programming as is , I am not aware of .hpp , I am sorry for the inconvenience
